### ISSUE TITLE
Issue with New version 7.6.0

### ISSUE THREAD

**Issue by sghazagh** [googlei18n/libphonenumber#1306]
I used version 7.5.2 in my project and it was working perfectly for Australia.
Tried to update to version 7.6.0 and The app crashes on this line:  

`Phonenumber.PhoneNumber ausNumberProto = phoneUtil.parse(ausNumberstr,"AU");`

The debug says this:
************************************
```
08-31 19:33:27.659 4068-4068/au.com.elar_systems.www.doky E/AndroidRuntime: FATAL EXCEPTION: main
                                                                            Process: au.com.elar_systems.www.doky, PID: 4068
                                                                            java.lang.NoClassDefFoundError: com.google.i18n.phonenumbers.nano.Phonemetadata$PhoneMetadata
                                                                                at com.google.i18n.phonenumbers.MultiFileMetadataSourceImpl.getMetadataForRegion(MultiFileMetadataSourceImpl.java:71)
                                                                                at com.google.i18n.phonenumbers.PhoneNumberUtil.getMetadataForRegion(PhoneNumberUtil.java:2122)
                                                                                at com.google.i18n.phonenumbers.PhoneNumberUtil.parseHelper(PhoneNumberUtil.java:2981)
                                                                                at com.google.i18n.phonenumbers.PhoneNumberUtil.parse(PhoneNumberUtil.java:2842)
                                                                                at com.google.i18n.phonenumbers.PhoneNumberUtil.parse(PhoneNumberUtil.java:2832)
                                                                                at au.com.elar_systems.www.doky.MainActivity.onCreate(MainActivity.java:500)
                                                                                at android.app.Activity.performCreate(Activity.java:6500)
                                                                                at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1120)
                                                                                at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3072)
                                                                                at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3218)
                                                                                at android.app.ActivityThread.access$1000(ActivityThread.java:198)
                                                                                at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1676)
                                                                                at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                at android.os.Looper.loop(Looper.java:145)
                                                                                at android.app.ActivityThread.main(ActivityThread.java:6837)
                                                                                at java.lang.reflect.Method.invoke(Native Method)
                                                                                at java.lang.reflect.Method.invoke(Method.java:372)
                                                                                at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1404)
                                                                                at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1199)
```
*********************************

changed back to version 7.5.2 and all good again.

**Comment by keghani** [comment]
Please see the 7.6.0 release announcement for how to fix this: https://github.com/googlei18n/libphonenumber/releases/tag/libphonenumber-7.6.0

**Comment by sghazagh** [comment]
Hi I didn't get what I actually have to change in my code.
For dependency, I am using Gradle. Can you please advise how I can add this dependency in my project?

thanks for your help. I am really short in time and want to implement this new release as well.
I appreciate your help...

**Comment by keghani** [comment]
I don't know how to add dependencies in Gradle :( Maybe people on the [discussion group](https://groups.google.com/forum/#!forum/libphonenumber-discuss) would know. All you should have to do is add a dependency for protobuf-javanano, in a similar way that you depend on libphonenumber.

**Comment by sghazagh** [comment]
I found it.Write it here for whom may need it.
To add protobuf-nano to your Android project and this dependency to your Gradle file:

compile group: 'com.google.protobuf.nano', name: 'protobuf-javanano', version: '3.0.0-alpha-7'

How did I find that:
Sear in mvnrepository.com for protobuf-nano

You see the Maven dependency is what Keghani has added on her post.

There is a tab for "Gradle" too. Use that one for your Gradle project.

@Keghani: Please refer this to other if they were looking for that....
I post the result if the compile also done successfully and my project worked too....

**Comment by penmetsaa** [comment]
@sghazagh 
Thanks so much for sharing this info. :)

**Comment by sghazagh** [comment]
You're welcome :)
