### ISSUE TITLE
Segmentation fault using libphonenumber with Boost 1.65.1

### ISSUE THREAD

**Issue by schoenenberg** [googlei18n/libphonenumber#2027]
Hello,
I upgraded my boost version from 1.53 to 1.65.1. Now I am getting a segmentation fault in my application. Please help me fixing this problem. If you need any further information, please tell me. I appreciate any help.

OS: CentOS Linux release 7.2.1511 (Core)
Compiler: GCC 4.8.5
Boost Version: 1.65.1

My code part using libphonenumber:
``` cpp
i18n::phonenumbers::PhoneNumberUtil* phoneUtil = i18n::phonenumbers::PhoneNumberUtil::GetInstance();
i18n::phonenumbers::PhoneNumber* phoneNumberProto = new i18n::phonenumbers::PhoneNumber();

if (i18n::phonenumbers::PhoneNumberUtil::ErrorType::NO_PARSING_ERROR == phoneUtil->Parse(number, country_iso2, phoneNumberProto))
{
	if (phoneUtil->IsValidNumber(*phoneNumberProto))
	{
		std::string normalised_number;
		phoneUtil->Format(*phoneNumberProto, i18n::phonenumbers::PhoneNumberUtil::PhoneNumberFormat::INTERNATIONAL, &normalised_number);

		item->set_formattedNumber(normalised_number);

		returnValue = OK_CONTINUE;
	}
	else
	{
		LOG_ERROR("Phone number is not valid!");
	}
}
else
{
	LOG_ERROR("Phone number parse error!");
}

delete phoneNumberProto;
```

This is the full backtrace:
```
Program received signal SIGSEGV, Segmentation fault.
malloc_consolidate (av=av@entry=0x7ffff4f22760 <main_arena>) at malloc.c:4146
4146              nextsize = chunksize(nextchunk);
(gdb) bt full
#0  malloc_consolidate (av=av@entry=0x7ffff4f22760 <main_arena>) at malloc.c:4146
        fb = <optimized out>
        maxfb = 0x7ffff4f227b0 <main_arena+80>
        p = 0x7ffff4f227b8 <main_arena+88>
        nextp = 0x8c6a10
        unsorted_bin = 0x7ffff4f227b8 <main_arena+88>
        first_unsorted = <optimized out>
        nextchunk = 0x7ffff57e93f8
        size = 9202752
        nextsize = <optimized out>
        prevsize = <optimized out>
        nextinuse = <optimized out>
        bck = <optimized out>
        fwd = <optimized out>
#1  0x00007ffff4be4ec6 in _int_free (av=0x7ffff4f22760 <main_arena>, p=0xb24dc0, have_lock=0) at malloc.c:4052
        size = 123456
        fb = <optimized out>
        nextchunk = 0xb25b70
        nextsize = 119952
        nextinuse = <optimized out>
        prevsize = <optimized out>
        bck = <optimized out>
        fwd = <optimized out>
        errstr = 0x0
        locked = <optimized out>
#2  0x00007ffff6aed5ef in deallocate (this=<optimized out>, __p=<optimized out>) at /usr/include/c++/4.8.2/ext/new_allocator.h:110
No locals.
#3  _M_deallocate (this=<optimized out>, __n=<optimized out>, __p=<optimized out>) at /usr/include/c++/4.8.2/bits/stl_vector.h:174
No locals.
#4  ~_Vector_base (this=0x8f6ea0, __in_chrg=<optimized out>) at /usr/include/c++/4.8.2/bits/stl_vector.h:160
No locals.
#5  ~vector (this=0x8f6ea0, __in_chrg=<optimized out>) at /usr/include/c++/4.8.2/bits/stl_vector.h:416
No locals.
#6  checked_delete<std::vector<std::pair<int, std::list<std::basic_string<char> >*> > > (x=0x8f6ea0) at /usr/include/boost/core/checked_delete.hpp:34
No locals.
#7  ~scoped_ptr (this=0x8c5560, __in_chrg=<optimized out>) at /usr/include/boost/smart_ptr/scoped_ptr.hpp:88
No locals.
#8  i18n::phonenumbers::PhoneNumberUtil::~PhoneNumberUtil (this=0x8c5540, __in_chrg=<optimized out>) at /home/schoenenberg/git/assets/tnn/lib_src/libphonenumber-8.8.5/cpp/src/phonenumbers/phonenumberutil.cc:810
No locals.
#9  0x00007ffff6aed6c9 in i18n::phonenumbers::PhoneNumberUtil::~PhoneNumberUtil (this=0x8c5540, __in_chrg=<optimized out>) at /home/schoenenberg/git/assets/tnn/lib_src/libphonenumber-8.8.5/cpp/src/phonenumbers/phonenumberutil.cc:814
No locals.
#10 0x00007ffff4ba11da in __cxa_finalize (d=0x7ffff6d4e960) at cxa_finalize.c:55
        check = 235
        cxafn = <optimized out>
        cxaarg = <optimized out>
        f = 0x8b43c0
        funcs = 0x8b4290
#11 0x00007ffff6ad8eb3 in __do_global_dtors_aux () from /home/schoenenberg/git/assets/tnn/lib/libphonenumber.so.8
No symbol table info available.
#12 0x00007fffffffdef0 in ?? ()
No symbol table info available.
#13 0x00007ffff7deaa1a in _dl_fini () at dl-fini.c:253
        array = 0x7ffff6d4e950
        i = 0
        nmaps = 32767
        nloaded = <optimized out>
        i = 7
        l = 0x7ffff7fd09b8
        ns = 140737299223002
        maps = 0x7fffffffdcd0
        maps_size = 9126848
        do_audit = -134411848
Backtrace stopped: frame did not save the PC
```

**Comment by keghani** [comment]
Thank you for using libphonenumber!

The problem doesn't seem to be with our repository, and we're not familiar with the setup.

I'll leave this open for now in case other contributors can help. But we can't provide support for setup on various machines, and if no one responds for a while I'll close it since it's not an issue with the library.

Consider posting to the [discussion
group](https://groups.google.com/forum/#!forum/libphonenumber-discuss) as well.

**Comment by schoenenberg** [comment]
Thank you for your answer! The last week I tried to find an answer to this problem. But nothing worked. So I went back to Boost 1.63.0 and now it works well again.
I am not sure what happend to be the issue in this, the compiler, the OS, the libraries or libphonenumber. Whatever, thanks guys and keep up the good work on this library. It is really great!

**Comment by keghani** [comment]
Thank you for the kind words!
