### ISSUE TITLE
Getting  ConcurrentModificationException when trying to parse a number on android 

### ISSUE THREAD

**Issue by suraj9781** [googlei18n/libphonenumber#606]
Hi,

I got a ConcurrentModificationException at one instance while parsing the number .I am using java version 7.0.1
Following is the stack trace:
ANDROID_VERSION=5.0.1
PHONE_MODEL=Nexus 4
STACK_TRACE=java.util.ConcurrentModificationException
at java.util.HashMap$HashIterator.nextEntry(HashMap.java:787)
at java.util.HashMap$KeyIterator.next(HashMap.java:814)
at java.util.jar.JarVerifier.readCertificates(JarVerifier.java:266)
at java.util.jar.JarFile.getInputStream(JarFile.java:380)
at libcore.net.url.JarURLConnectionImpl.getInputStream(JarURLConnectionImpl.java:222)
at java.net.URL.openStream(URL.java:470)
at java.lang.ClassLoader.getResourceAsStream(ClassLoader.java:444)
at java.lang.Class.getResourceAsStream(Class.java:1334)
at com.google.i18n.phonenumbers.PhoneNumberUtil$1.loadMetadata(PhoneNumberUtil.java:62)
at com.google.i18n.phonenumbers.PhoneNumberUtil.loadMetadataFromFile(PhoneNumberUtil.java:616)
at com.google.i18n.phonenumbers.PhoneNumberUtil.getMetadataForRegion(PhoneNumberUtil.java:2043)
at com.google.i18n.phonenumbers.PhoneNumberUtil.parseHelper(PhoneNumberUtil.java:2901)
at com.google.i18n.phonenumbers.PhoneNumberUtil.parse(PhoneNumberUtil.java:2763)
at com.google.i18n.phonenumbers.PhoneNumberUtil.parse(PhoneNumberUtil.java:2753)

**Comment by dlyongemallo** [comment]
Are you running the library in a multi-threaded environment?

**Comment by suraj9781** [comment]
yes .I have synchronized my function so i didn't receive a exception  till now

**Comment by dlyongemallo** [comment]
Can you clarify? You are running in a multi-threaded environment. The function which calls libphonenumber is synchronised. Are other synchronised functions also calling the phone number library? Have you tried guarding the call with a lock?

**Comment by suraj9781** [comment]
I had contact sync function which was getting called from multiple instances  so by synchronizing this sync function i am able to resolve this issue now
