### ISSUE TITLE
Build fails inside of Closure Compiler.

### ISSUE THREAD

**Issue by nathanhammond** [googlei18n/libphonenumber#630]
Given a completely clean build setup, all deps in the correct location, and this command:
```bash
$ ant -f javascript/build.xml compile-demo
````
libphonenumber fails to compile, throwing this error (modified paths to slice off my home directory):

```
compile-demo:
     [exec] calcdeps.py: Scanning files...
     [exec] calcdeps.py: Finding Closure dependencies...
     [exec] calcdeps.py: Compiling with the following command: java -jar /libphonenumber/javascript/../../closure-compiler/build/compiler.jar --js /closure-library/closure/goog/base.js --js /closure-library/closure/goog/debug/error.js --js /closure-library/closure/goog/dom/nodetype.js --js /closure-library/closure/goog/string/string.js --js /closure-library/closure/goog/asserts/asserts.js --js /closure-library/closure/goog/array/array.js --js /closure-library/closure/goog/labs/useragent/util.js --js /closure-library/closure/goog/object/object.js --js /closure-library/closure/goog/labs/useragent/browser.js --js /closure-library/closure/goog/labs/useragent/engine.js --js /closure-library/closure/goog/labs/useragent/platform.js --js /closure-library/closure/goog/useragent/useragent.js --js /closure-library/closure/goog/dom/browserfeature.js --js /closure-library/closure/goog/dom/tagname.js --js /closure-library/closure/goog/dom/tags.js --js /closure-library/closure/goog/string/typedstring.js --js /closure-library/closure/goog/string/const.js --js /closure-library/closure/goog/html/safestyle.js --js /closure-library/closure/goog/html/safestylesheet.js --js /closure-library/closure/goog/i18n/bidi.js --js /closure-library/closure/goog/html/safeurl.js --js /closure-library/closure/goog/html/trustedresourceurl.js --js /closure-library/closure/goog/html/safehtml.js --js /closure-library/closure/goog/dom/safe.js --js /closure-library/closure/goog/math/math.js --js /closure-library/closure/goog/math/coordinate.js --js /closure-library/closure/goog/math/size.js --js /closure-library/closure/goog/dom/dom.js --js /closure-library/closure/goog/json/json.js --js /closure-library/closure/goog/proto2/fielddescriptor.js --js /closure-library/closure/goog/proto2/descriptor.js --js /closure-library/closure/goog/proto2/message.js --js /closure-library/closure/goog/proto2/serializer.js --js /closure-library/closure/goog/proto2/objectserializer.js --js /closure-library/closure/goog/string/stringbuffer.js --js i18n/phonenumbers/phonemetadata.pb.js --js i18n/phonenumbers/phonenumber.pb.js --js /closure-library/closure/goog/proto2/lazydeserializer.js --js /closure-library/closure/goog/proto2/pbliteserializer.js --js i18n/phonenumbers/metadata.js --js i18n/phonenumbers/phonenumberutil.js --js i18n/phonenumbers/asyoutypeformatter.js --js i18n/phonenumbers/demo.js --output_wrapper=(function(){%output%})(); --compilation_level=ADVANCED_OPTIMIZATIONS --warning_level=VERBOSE --jscomp_error=accessControls --jscomp_error=ambiguousFunctionDecl --jscomp_error=checkDebuggerStatement --jscomp_error=checkRegExp --jscomp_error=checkTypes --jscomp_error=checkVars --jscomp_error=const --jscomp_error=constantProperty --jscomp_error=deprecated --jscomp_error=duplicate --jscomp_error=duplicateMessage --jscomp_error=es5Strict --jscomp_error=externsValidation --jscomp_error=fileoverviewTags --jscomp_error=globalThis --jscomp_error=internetExplorerChecks --jscomp_error=invalidCasts --jscomp_error=misplacedTypeAnnotation --jscomp_error=missingProperties --jscomp_error=nonStandardJsDocs --jscomp_error=strictModuleDepCheck --jscomp_error=suspiciousCode --jscomp_error=typeInvalidation --jscomp_error=undefinedNames --jscomp_error=undefinedVars --jscomp_error=unknownDefines --jscomp_error=uselessCode --jscomp_error=visibility
     [exec] java.lang.NoSuchMethodError: com.google.javascript.rhino.jstype.RecordType.defineDeclaredProperty(Ljava/lang/String;Lcom/google/javascript/rhino/jstype/JSType;Lcom/google/javascript/rhino/Node;)Z
     [exec] 	at com.google.javascript.rhino.jstype.RecordType.<init>(RecordType.java:96)
     [exec] 	at com.google.javascript.rhino.jstype.RecordTypeBuilder.build(RecordTypeBuilder.java:92)
     [exec] 	at com.google.javascript.rhino.jstype.JSTypeRegistry.createRecordTypeFromNodes(JSTypeRegistry.java:1813)
     [exec] 	at com.google.javascript.rhino.jstype.JSTypeRegistry.createFromTypeNodesInternal(JSTypeRegistry.java:1588)
     [exec] 	at com.google.javascript.rhino.jstype.JSTypeRegistry.createFromTypeNodesInternal(JSTypeRegistry.java:1622)
     [exec] 	at com.google.javascript.rhino.jstype.JSTypeRegistry.createFromTypeNodesInternal(JSTypeRegistry.java:1592)
     [exec] 	at com.google.javascript.rhino.jstype.JSTypeRegistry.createFromTypeNodes(JSTypeRegistry.java:1580)
     [exec] 	at com.google.javascript.rhino.JSTypeExpression.evaluate(JSTypeExpression.java:100)
     [exec] 	at com.google.javascript.jscomp.FunctionTypeBuilder.inferThisType(FunctionTypeBuilder.java:450)
     [exec] 	at com.google.javascript.jscomp.FunctionTypeBuilder.inferThisType(FunctionTypeBuilder.java:428)
     [exec] 	at com.google.javascript.jscomp.TypedScopeCreator$AbstractScopeBuilder.createFunctionTypeFromNodes(TypedScopeCreator.java:967)
     [exec] 	at com.google.javascript.jscomp.TypedScopeCreator$AbstractScopeBuilder.defineFunctionLiteral(TypedScopeCreator.java:792)
     [exec] 	at com.google.javascript.jscomp.TypedScopeCreator$AbstractScopeBuilder.visit(TypedScopeCreator.java:522)
     [exec] 	at com.google.javascript.jscomp.TypedScopeCreator$GlobalScopeBuilder.visit(TypedScopeCreator.java:1879)
     [exec] 	at com.google.javascript.jscomp.NodeTraversal.traverseBranch(NodeTraversal.java:588)
     [exec] 	at com.google.javascript.jscomp.NodeTraversal.traverseBranch(NodeTraversal.java:582)
     [exec] 	at com.google.javascript.jscomp.NodeTraversal.traverseBranch(NodeTraversal.java:582)
     [exec] 	at com.google.javascript.jscomp.NodeTraversal.traverseBranch(NodeTraversal.java:582)
     [exec] 	at com.google.javascript.jscomp.NodeTraversal.traverseBranch(NodeTraversal.java:582)
     [exec] 	at com.google.javascript.jscomp.NodeTraversal.traverseBranch(NodeTraversal.java:582)
     [exec] 	at com.google.javascript.jscomp.NodeTraversal.traverse(NodeTraversal.java:291)
     [exec] 	at com.google.javascript.jscomp.NodeTraversal.traverse(NodeTraversal.java:540)
     [exec] 	at com.google.javascript.jscomp.TypedScopeCreator.createScope(TypedScopeCreator.java:231)
     [exec] 	at com.google.javascript.jscomp.MemoizedScopeCreator.createScope(MemoizedScopeCreator.java:82)
     [exec] 	at com.google.javascript.jscomp.PassConfig.regenerateGlobalTypedScope(PassConfig.java:68)
     [exec] 	at com.google.javascript.jscomp.DefaultPassConfig$GlobalTypeResolver.process(DefaultPassConfig.java:1541)
     [exec] 	at com.google.javascript.jscomp.PhaseOptimizer$NamedPass.process(PhaseOptimizer.java:285)
     [exec] 	at com.google.javascript.jscomp.PhaseOptimizer.process(PhaseOptimizer.java:217)
     [exec] 	at com.google.javascript.jscomp.Compiler.check(Compiler.java:844)
     [exec] 	at com.google.javascript.jscomp.Compiler.compileInternal(Compiler.java:757)
     [exec] 	at com.google.javascript.jscomp.Compiler.access$000(Compiler.java:95)
     [exec] 	at com.google.javascript.jscomp.Compiler$3.call(Compiler.java:656)
     [exec] 	at com.google.javascript.jscomp.Compiler$3.call(Compiler.java:653)
     [exec] 	at com.google.javascript.jscomp.Compiler$4.call(Compiler.java:700)
     [exec] 	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
     [exec] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
     [exec] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
     [exec] 	at java.lang.Thread.run(Thread.java:744)
     [exec] calcdeps.py: JavaScript compilation failed.

BUILD FAILED
/libphonenumber/javascript/build.xml:100: The following error occurred while executing this line:
/libphonenumber/javascript/build.xml:23: exec returned: 1
```
It appears to be a Closure Compiler issue, but I'm wondering how you're able to actually get it to build? (@andyst I noticed that you committed demo-compiled in just the past few days.) Which versions of the dependent repos are you running?

(I maintain https://github.com/nathanhammond/libphonenumber to make it easier to use libphonenumber.)

**Comment by nathanhammond** [comment]
Closing as out of date.

**Comment by srinaikcotky** [comment]
@nathanhammond what was the solution to your problem? I am still having trouble at that very command.

**Comment by nathanhammond** [comment]
Just update all of your dependencies. It was a transient failure due to deps issues.
