### ISSUE TITLE
Unit test fails

### ISSUE THREAD

**Issue by Pimm** [googlei18n/libphonenumber#803]
Unit tests fail for me since 994c913514a7dbd0e52fbb3646e9abd5270a4eef (which seems to be a problem in the unit test; not the lib):

```
java.lang.AssertionError: Test input data should always parse correctly: +4640404 (SE)
	at com.google.i18n.phonenumbers.ShortNumberInfoTest.parse(ShortNumberInfoTest.java:351)
	at com.google.i18n.phonenumbers.ShortNumberInfoTest.testCountryCallingCodeIsNotIgnored(ShortNumberInfoTest.java:339)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at android.test.AndroidTestRunner.runTest(AndroidTestRunner.java:191)
	at android.test.AndroidTestRunner.runTest(AndroidTestRunner.java:176)
	at android.test.InstrumentationTestRunner.onStart(InstrumentationTestRunner.java:554)
	at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:1701)
Caused by: Error type: INVALID_COUNTRY_CODE. Could not interpret numbers after plus-sign.
	at com.google.i18n.phonenumbers.PhoneNumberUtil.parseHelper(PhoneNumberUtil.java:2846)
	at com.google.i18n.phonenumbers.PhoneNumberUtil.parse(PhoneNumberUtil.java:2687)
	at com.google.i18n.phonenumbers.PhoneNumberUtil.parse(PhoneNumberUtil.java:2677)
	at com.google.i18n.phonenumbers.ShortNumberInfoTest.parse(ShortNumberInfoTest.java:349)
	... 13 more
```

**Comment by mihaelacr-google** [comment]
Hi!

Thanks for the bug report!

We are aware of this issue and we will fix it with the new release (in 1-2 days). It is a problem with files which are automatically generated by ant.

In order to build the new files correctly you have to run:
` ant test -Dtest=none`

After running this command, the tests should run correctly.

**Comment by mihaelacr-google** [comment]
The tests should be passing now, I sent a pull request yesterday. I am closing this issue.
