### ISSUE TITLE
Initial call to getCountryCodeForRegion very slow on Android

### ISSUE THREAD

**Issue by guelo** [googlei18n/libphonenumber#940]
The initial call to getCountryCodeForRegion on Android can be very slow. I've tested my apk on some slower phones taking up to 2 seconds.

The slowness occurs when calling ```Class.getResourceAsStream``` and that ends up in ```ZipFile``` where it seems to be unziping the apk to get access to the ProtoBuff data files inside. Here's the stack trace,

     at java.util.zip.ZipFile.readCentralDir(ZipFile.java:407)
     at java.util.zip.ZipFile.<init>(ZipFile.java:175)
     at java.util.zip.ZipFile.<init>(ZipFile.java:131)
     at dalvik.system.DexPathList$Element.maybeInit(DexPathList.java:452)
     at dalvik.system.DexPathList$Element.findResource(DexPathList.java:499)
     at dalvik.system.DexPathList.findResource(DexPathList.java:360)
     at dalvik.system.BaseDexClassLoader.findResource(BaseDexClassLoader.java:67)
     at java.lang.ClassLoader.getResource(ClassLoader.java:403)
     at java.lang.ClassLoader.getResourceAsStream(ClassLoader.java:442)
     at java.lang.Class.getResourceAsStream(Class.java:1169)
     at com.google.i18n.phonenumbers.PhoneNumberUtil$1.loadMetadata(PhoneNumberUtil.java:59)
     at com.google.i18n.phonenumbers.MultiFileMetadataSourceImpl.loadMetadataFromFile(MultiFileMetadataSourceImpl.java:100)
     at com.google.i18n.phonenumbers.MultiFileMetadataSourceImpl.getMetadataForRegion(MultiFileMetadataSourceImpl.java:79)
     at com.google.i18n.phonenumbers.PhoneNumberUtil.getMetadataForRegion(PhoneNumberUtil.java:1994)
     at com.google.i18n.phonenumbers.PhoneNumberUtil.getCountryCodeForValidRegion(PhoneNumberUtil.java:2155)
     at com.google.i18n.phonenumbers.PhoneNumberUtil.getCountryCodeForRegion(PhoneNumberUtil.java:2143)

The problem is probably worse on my app then typical because my zipped apk is 14MB. 

Looking at the source code, the data that we want is already in memory in CountryCodeToRegionCodeMap, so it doesn't seem like you need to load it from the apk.

**Comment by guelo** [comment]
Calling java.lang.Class.getResourceAsStream() in the Android world is a problem because the files have to be unziped out of the apk. Android provides more efficient methods to avoid this problem such as AssetManager.open(String fileName) and Resources.openRawResource(int id).

**Comment by dlyongemallo** [comment]
That's exactly the solution.

Add the metadata binary files to your app as asset, then use Application.getContext().getAssets().open(...) to read it. 

Then create your instance of PhoneNumberUtil using createInstance(metadataLoader):
https://github.com/googlei18n/libphonenumber/blob/fe5bfd4/java/libphonenumber/src/com/google/i18n/phonenumbers/PhoneNumberUtil.java#L989-L994

You'd have to copy the metadata binary files into your app's assets, but you can remove the same from the library, so there is no net increase of app size. The result is that the files are read as native Android assets and hence optimised for speed.

**Comment by guelo** [comment]
Copying files into your app is not a good solution because you lose the advantage of being able to rely on the upstream library for updates.

Also, once you're copying files into the app it seems easier to copy CountryCodeToRegionCodeMap.java and avoid reading protobuf files entirely.

**Comment by dlyongemallo** [comment]
You can easily automate updating your assets as part of your build process.

The first call to loadMetadataFromFile always takes a long time. It just happens that getCountryCodeForRegion is the first call you're making that ends up calling loadMetadataFromFile.

getCountryCodeForRegion is given a region, and returns a country calling code. The data in CountryCodeToRegionCodeMap is in the other direction: given a countrying calling code, return a region. One cannot quickly derive one from the other.

You could create a static inverse map to do the region to country calling code mapping, but what would be the point? At some point, the library has to load the metadata from file. It might as well be in getCountryCodeForRegion as anywhere.

**Comment by a396901990** [comment]
initial and check any number before you use it
